version: '3.3'
services:
  mediawiki:
    image: mediawiki-ldap:latest
#    build: ./build/Dockerfile
    container_name: mediawiki-app
    restart: unless-stopped
    environment:
      - LDAP_BASE=${LDAP_BASE}
      - LDAP_SERVER_NAME=${LDAP_SERVER_NAME}
      - LDAP_SERVER_PORT=${LDAP_SERVER_PORT}
      - LDAP_DOMAINNAME=${LDAP_DOMAINNAME}
      - LDAP_ENCTYPE=${LDAP_ENCTYPE}
      - LDAP_USER_ATTR=${LDAP_USER_ATTR}
      - LDAP_BIND_USER=${LDAP_BIND_USER}
      - LDAP_BIND_PASS=${LDAP_BIND_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - WIKI_NAME=${WIKI_NAME}
      - WIKI_ADMIN=${WIKI_ADMIN}
      - WIKI_ADMIN_PASS=${WIKI_ADMIN_PASS}
      - WIKI_URL=${WIKI_URL}
      - WIKI_LANG=${WIKI_LANG}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediawiki.rule=Host(`wiki.yourdomain.local`)"
      - "traefik.http.routers.mediawiki.entrypoints=websecure"
      - "traefik.http.routers.mediawiki.tls.certresolver=mytlschallenge"

    volumes:
      - mediawiki-data:/var/www/html/
      - mediawiki-logs:/log/mediawiki
#      - /opt/docker-compose/mediawiki/php.ini:/usr/local/etc/php/conf.d/mediawiki.ini
    expose:
      - '80'
    networks:
      - proxy

  mariadb:
    image: mariadb
    container_name: mediawiki-db
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - mediawiki-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_RANDOM_ROOT_PASSWORD='yes'

volumes:
  mediawiki-db:
    driver: local
  mediawiki-data:
    driver: local
  mediawiki-logs:
    driver: local

networks:
  proxy:
    external: true
